---
kind: pipeline
name: nightly

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  pull: always
  image: rustlang/rust:nightly
  commands:
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  - cargo fmt --check
  - cargo clippy --all-features -Z unstable-options --future-incompat-report
  failure: ignore

trigger:
  event:
  - push

---
kind: pipeline
name: stable

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: rust:latest
  commands:
  - cargo fetch

- name: clippy
  image: rust:latest
  commands:
  - rustup component add clippy
  - cargo clippy --all-features
  depends_on:
  - fetch

- name: fmt
  image: rust:latest
  commands:
  - rustup component add rustfmt
  - cargo fmt --check
  depends_on:
  - fetch

- name: deny
  image: rust:latest
  commands:
  - cargo install --locked cargo-deny
  - cargo deny check
  depends_on:
  - fetch

- name: build
  image: rust:latest
  commands:
  - cargo build --all-features
  depends_on:
  - deny

- name: test
  image: rust:latest
  commands:
  - cargo test --all-features
  depends_on:
  - build

trigger:
  event:
  - push
