[package]
name = "chilloutvr"
version = "0.2.1"
edition = "2021"
license = "MPL-2.0"
authors = ["ljoonal"]
description = "Unofficial rust types of ChilloutVR's API"
repository = "https://github.com/onlivfe/chilloutvr_rs"
documentation = "https://docs.rs/chilloutvr"
keywords = ["cvr", "chilloutvr", "api", "rest", "websocket"]
categories = ["api-bindings", "games"]

include = ["src", "Cargo.toml", "LICENSE", "README.md"]

[badges]
maintenance = { status = "experimental" }

[lib]
name = "chilloutvr"
path = "src/lib.rs"

[features]

default = ["http", "ws"]

# Enable models that relate are used in HTTP requests
http = ["racal"]
http_client = ["http", "reqwest", "racal/reqwest", "governor", "async-trait"]

# Enable models that are used in WS requests
ws = []
ws_client = ["ws", "tokio", "tokio-tungstenite", "tokio-stream", "futures-util", "dep:http", "base64", "rand"]

# By default we allows deserializing some things partially even with errors.
# Like skipping array entries with errors, which is not wanted for tests though.
debug = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "2.2", features = ["time_0_3"] }
time = { version = "0.3", default-features = false, features = [
	"serde-well-known",
] }
serde_json = { version = "1" }
strum = { version = "0.24", features = ["derive"] }

# API client specifics
racal = { version = "0.3.2", optional = true }
#racal = { path = "../racal", features = ["reqwest"], optional = true }
governor = { version = "0.5", optional = true }
tokio = { version = "1", optional = true, features = ["macros"]}
tokio-stream = { version = "0.1", optional = true}
futures-util = { version = "0.3", optional = true}
http = { version = "0.2", optional = true }
base64 = { version = "0.21", optional = true }
rand = { version = "0.8", optional = true }
async-trait = { version = "0.1", optional = true }

[dependencies.reqwest]
optional = true
version = "0.11"
default-features = false
features = ["json", "rustls-tls"]

[dependencies.tokio-tungstenite]
optional = true
version = "0.18"
default-features = false
features = ["rustls-tls-webpki-roots", "connect"]

[dev-dependencies]
tokio-test = "0.4"
tokio = { version = "1", features = ["rt", "macros"]}
once_cell = "1.17"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "nightly"]
